GET http://localhost:4000/content

###

GET http://localhost:4000/content/606c8dd0199fd920709ff619

###

POST http://localhost:4000/content
Content-Type: application/json

{
    "userId": -1,
    "username": "System",
    "contentTitle": "Hello World",
    "contentBody": "Welcome! We hope you enjoy your stay!👋"
}

###

DELETE http://localhost:4000/content/606c8dd0199fd920709ff619


###

PATCH  http://localhost:4000/content/606c8d77199fd920709ff618
Content-Type: application/json

{
    "contentBody": "Welcome! We hope you enjoy your stay!👋"
}