GET http://localhost:4000/content

###

GET http://localhost:4000/content/606c8dd0199fd920709ff619

###

POST http://localhost:4000/content
Content-Type: application/json

{
    "userId": -1,
    "username": "System",
    "contentTitle": "Test ✅",
    "contentBody": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia, molestiae quas vel sint commodi."
}

###

POST http://localhost:4000/content
Content-Type: application/json

{
    "userId": -1,
    "username": "System",
    "contentTitle": "Hello World",
    "contentBody": "Welcome! We hope you enjoy your stay! 👋",
    "imageLink": "https://static.wixstatic.com/media/e5527e_e41291e94a7946968747654b4a944967~mv2.gif"
}

###

DELETE http://localhost:4000/content/606e37d07482c020ec97cbb8


###

PATCH  http://localhost:4000/content/606c8d77199fd920709ff618
Content-Type: application/json

{
    "contentBody": "Welcome! We hope you enjoy your stay!👋"
}